### ISSUE TITLE
Ruby Keyword Parameters Sunsetted in Ruby 3.0

### ISSUE THREAD

**Issue by ericadohring** [pivotal-legacy/pivotal_ide_prefs#84]
Ruby 3.0 has officially deprecated keyword arguments. This is causing lines 56 and 67 of our ide_prefs to error out. 

```/Users/pivotal/workspace/pivotal_ide_prefs/cli/lib/cli/configuration/repo_configuration.rb:4:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from ./bin/ide_prefs:56:in `new'
	from ./bin/ide_prefs:56:in `<main>'```

```/Users/pivotal/workspace/pivotal_ide_prefs/ide_prefs/lib/ide_prefs/commands/install_prefs.rb:4:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from ./bin/ide_prefs:67:in `new'
	from ./bin/ide_prefs:67:in `<main>'```

The fix seems to be prefacing the initializer with a **

```-repo_configuration = Cli::Configuration::RepoConfiguration.new(repo_config_options)
+repo_configuration = Cli::Configuration::RepoConfiguration.new(**repo_config_options)```
and
```-Cli::CommandFactory.new(ARGV.last).command.new(repos).execute
+Cli::CommandFactory.new(ARGV.last).command.new(**repos).execute```

I'm waiting on push access to submit a PR, but I believe that will work for anyone waiting in the meantime. I have yet to test this with previous versions of ruby to ensure backwards compatibility. 

https://github.com/pivotal-legacy/pivotal_ide_prefs/blob/master/cli/bin/ide_prefs.rb#L56
https://github.com/pivotal-legacy/pivotal_ide_prefs/blob/master/cli/bin/ide_prefs.rb#L67

**Comment by infews** [comment]
@professor can you please transfer this issue to the new repo?
